### ISSUE TITLE
Hacking with npm

### ISSUE THREAD

**Issue by nono** [cozy/cozy-client-js#12]
It looks like it's not currently possible to build the lib with npm 2:

```sh
$ npm -v
2.15.4
$ npm run build

> cozy-client-js@0.0.1 build /home/nono/cc/client-js
> NODE_ENV=production webpack

Hash: 75d19d4238bfe0a779b7
Version: webpack 1.13.3
Time: 528ms
             Asset     Size  Chunks             Chunk Names
    cozy-client.js  14.2 kB       0  [emitted]  main
cozy-client.js.map  16.3 kB       0  [emitted]  main
   [0] multi main 52 bytes {0} [built] [2 errors]
    + 2 hidden modules

ERROR in multi main
Module not found: Error: Cannot resolve module 'regenerator-runtime/runtime' in /home/nono/cc/client-js
 @ multi main

ERROR in ./src/index.js
Module build failed: Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
Referenced from: /home/nono/cc/client-js/node_modules/standard/eslintrc.json
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.load (/home/nono/cc/client-js/node_modules/eslint/lib/config/plugins.js:129:26)
    at Array.forEach (native)
    at Object.loadAll (/home/nono/cc/client-js/node_modules/eslint/lib/config/plugins.js:151:21)
    at load (/home/nono/cc/client-js/node_modules/eslint/lib/config/config-file.js:504:21)
    at /home/nono/cc/client-js/node_modules/eslint/lib/config/config-file.js:391:36
    at Array.reduceRight (native)
    at applyExtends (/home/nono/cc/client-js/node_modules/eslint/lib/config/config-file.js:362:28)
    at Object.load (/home/nono/cc/client-js/node_modules/eslint/lib/config/config-file.js:529:22)
    at loadConfig (/home/nono/cc/client-js/node_modules/eslint/lib/config.js:63:33)
    at new Config (/home/nono/cc/client-js/node_modules/eslint/lib/config.js:226:38)
    at CLIEngine.executeOnText (/home/nono/cc/client-js/node_modules/eslint/lib/cli-engine.js:743:28)
    at Linter.lintText (/home/nono/cc/client-js/node_modules/standard/node_modules/standard-engine/index.js:65:59)
    at Object.standardLoader (/home/nono/cc/client-js/node_modules/standard-loader/index.js:20:12)
 @ multi main
```

**Comment by nono** [comment]
Well, not better with node 6 / npm 3:

```sh
$ npm run build

> cozy-client-js@0.0.1 build /home/nono/cc/client-js
> NODE_ENV=production webpack

Hash: 75d19d4238bfe0a779b7
Version: webpack 1.13.3
Time: 505ms
             Asset     Size  Chunks             Chunk Names
    cozy-client.js  14.2 kB       0  [emitted]  main
cozy-client.js.map  16.3 kB       0  [emitted]  main
   [0] multi main 52 bytes {0} [built] [2 errors]
    + 2 hidden modules

ERROR in multi main
Module not found: Error: Cannot resolve module 'regenerator-runtime/runtime' in /home/nono/cc/client-js
 @ multi main

ERROR in ./src/index.js
Module build failed: Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
Referenced from: /home/nono/cc/client-js/node_modules/standard/eslintrc.json
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.load (/home/nono/cc/client-js/node_modules/eslint/lib/config/plugins.js:129:26)
    at Array.forEach (native)
    at Object.loadAll (/home/nono/cc/client-js/node_modules/eslint/lib/config/plugins.js:151:21)
    at load (/home/nono/cc/client-js/node_modules/eslint/lib/config/config-file.js:504:21)
    at /home/nono/cc/client-js/node_modules/eslint/lib/config/config-file.js:391:36
    at Array.reduceRight (native)
    at applyExtends (/home/nono/cc/client-js/node_modules/eslint/lib/config/config-file.js:362:28)
    at Object.load (/home/nono/cc/client-js/node_modules/eslint/lib/config/config-file.js:529:22)
    at loadConfig (/home/nono/cc/client-js/node_modules/eslint/lib/config.js:63:33)
    at new Config (/home/nono/cc/client-js/node_modules/eslint/lib/config.js:226:38)
    at CLIEngine.executeOnText (/home/nono/cc/client-js/node_modules/eslint/lib/cli-engine.js:743:28)
    at Linter.lintText (/home/nono/cc/client-js/node_modules/standard/node_modules/standard-engine/index.js:65:59)
    at Object.standardLoader (/home/nono/cc/client-js/node_modules/standard-loader/index.js:20:12)
 @ multi main
$ npm -v
3.10.3
$ node -v
v6.6.0
```

**Comment by aenario** [comment]
Should we fix compatiblity with npm 2 or just warn about it ?

**Comment by nono** [comment]
If we can figure quickly a way to support npm 2, it's nice to have it. Else, a warning is good for me.

**Comment by aenario** [comment]
I think it was fixed with https://github.com/cozy/cozy-client-js/commit/7984cf7334d10dc8027b86cb7bcafb7b0ba3e137

**Comment by nono** [comment]
Yes, I can build it with node 4 /npm 2 now.
