### ISSUE TITLE
Installing for node does not work directly

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-client-js#199]
Some dependencies are missing if you want to develop a CLI app with cozy-client-js

```
$ yarn add cozy-client-js
$ node
> require('cozy-client-js')
module.js:491
    throw err;
    ^

Error: Cannot find module 'isomorphic-fetch'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/pbrowne/code/cozy/cozy-match-operations-bills/node_modules/cozy-client-js/dist/cozy-client.node.js:55:19)
    at __webpack_require__ (/Users/pbrowne/code/cozy/cozy-match-operations-bills/node_modules/cozy-client-js/dist/cozy-client.node.js:20:30)
    at Object.<anonymous> (/Users/pbrowne/code/cozy/cozy-match-operations-bills/node_modules/cozy-client-js/dist/cozy-client.node.js:47:2)
    at __webpack_require__ (/Users/pbrowne/code/cozy/cozy-match-operations-bills/node_modules/cozy-client-js/dist/cozy-client.node.js:20:30)
    at /Users/pbrowne/code/cozy/cozy-match-operations-bills/node_modules/cozy-client-js/dist/cozy-client.node.js:40:18
    at Object.<anonymous> (/Users/pbrowne/code/cozy/cozy-match-operations-bills/node_modules/cozy-client-js/dist/cozy-client.node.js:43:10)
```

Here's how to add them : 

```
$ yarn add isomorphic-fetch core-js regenerator-runtime btoa
```

**Comment by enguerran** [comment]
@ptbrowne could you confirm that #200 by @nono fixes this issue and thus this issue could be closed?

**Comment by ptbrowne** [comment]
Yes I confirm
